# You can use this file to create a conda environment for this pipeline:
#   conda env create -f environment.yml
name: nf-core-coproid-1.1dev
channels:
  - conda-forge
  - maxibor
  - bioconda
  - defaults
dependencies:
  - conda-forge::openblas=0.3.7
  - bioconda::adapterremoval=2.3.1
  - bioconda::bcftools=1.10.2
  - bioconda::bedtools=2.29.2
  - bioconda::blast=2.9.0
  - conda-forge::bokeh=2.0.1
  - bioconda::bowtie2=2.3.5.1
  - bioconda::damageprofiler=0.4.9
  - bioconda::fastqc=0.11.9
  - conda-forge::jupyter=1.0.0
  - bioconda::kraken2=2.0.8_beta
  - conda-forge::notebook=6.0.3
  - conda-forge::nbconvert=5.6.1
  - bioconda::nextflow=20.01.0
  - bioconda::pmdtools=0.60
  - bioconda::pysam=0.15.3
  - bioconda::samtools=1.10
  - maxibor::sourcepredict=0.5
  - conda-forge::scipy=1.4.1
  - conda-forge::matplotlib=3.2.1
  - bioconda::multiqc=1.7
  - conda-forge::jupyter_contrib_nbextensions=0.5.1
  - conda-forge::plotnine=0.6.0
  - conda-forge::markdown=3.2.1
  - conda-forge::pymdown-extensions=7.0
  - conda-forge::pygments=2.6.1
  - conda-forge::tbb=2020.1
